<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lap_buku_besar extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Sale_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        is_allowed($this->uri->segment(1),null);
        
        $this->template->load('template','laporan/buku_besar_category');
    }

    public function list_data($status) 
    {
        is_allowed($this->uri->segment(1),null);

        $view = '';

        if ($status === 'list_lancar') {
    		$view = 'Lancar';
    	}

    	if ($status === 'list_kurang_lancar') {
    		$view = 'Kurang Lancar';
    	}

    	if ($status === 'list_diragukan') {
    		$view = 'Diragukan';
    	}

    	if ($status === 'list_macet') {
    		$view = 'Macet';
    	}

        $data['lists_data'] = $this->Sale_model->getAllbyKeadaanCicilan($view);
        
        $this->template->load('template','laporan/list_bb', $data);
    }

 //    public function read($id) 
 //    {
 //        is_allowed($this->uri->segment(1),'read');
 //        $row = $this->Jenis_item_model->get_by_id($id);
 //        if ($row) {
 //            $data = array(
	// 	'jenis_item_id' => $row->jenis_item_id,
	// 	'nama_jenis_item' => $row->nama_jenis_item,
	//     );
 //            $this->template->load('template','jenis_item/jenis_item_read', $data);
 //        } else {
 //            $this->session->set_flashdata('message', 'Record Not Found');
 //            redirect(site_url('jenis_item'));
 //        }
 //    }

 //    public function create() 
 //    {
 //        is_allowed($this->uri->segment(1),'create');
 //        $data = array(
 //            'button' => 'Create',
 //            'action' => site_url('jenis_item/create_action'),
	//     'jenis_item_id' => set_value('jenis_item_id'),
	//     'nama_jenis_item' => set_value('nama_jenis_item'),
	// );
 //        $this->template->load('template','jenis_item/jenis_item_form', $data);
 //    }

}

/* End of file Jenis_item.php */
/* Location: ./application/controllers/Jenis_item.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-01 08:38:23 */
/* http://harviacode.com */
