<?php

require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lap_historypel extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Jenis_item_model');
        $this->load->model('Laporan_model');
        $this->load->model('Sale_model');
        $this->load->model('History_pembayaran_model');
        $this->load->model('Kategori_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        is_allowed($this->uri->segment(1),null);
        $this->template->load('template','laporan/history_pelanggan');
    }

    public function fetch_tabel_history_pelanggan()
    {
        $tbno = $this->input->post('tbno');
        $searchidtype = $this->input->post('typedata');

        $data['lists_data'] = $this->Laporan_model->getallPelangganHistoryDatawithSpecifiedID($tbno,$searchidtype);
        $data['classnyak'] = $this;
        $this->load->view('laporan/tabel_history_pelanggan', $data);
    }

    function getLastPaidCicilan($invoice)
    {
    	$data = $this->Laporan_model->getlastpaidcicilan($invoice);
    	return $data;
    }

    function getTotalKeterlambatanHari($invoice)
    {
    	$data = $this->Laporan_model->gettotalterlambathari($invoice);
    	return $data;
    }
}

/* End of file Jenis_item.php */
/* Location: ./application/controllers/Jenis_item.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-01 08:38:23 */
/* http://harviacode.com */
