<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lap_buku_besar extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Sale_model');
        $this->load->model('User_m');
        $this->load->model('Laporan_model');
        $this->load->model('Sale_detail_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        is_allowed($this->uri->segment(1),null);

        $data = array(
            'classnyak' => $this,
            'dataunit' => $this->User_m->getgroupusaha($this->session->userdata('unit_id'))
        );
        
        $this->template->load('template','laporan/buku_besar_category', $data);
    }

    public function list_data($status) 
    {
        is_allowed($this->uri->segment(1),null);

        $data['view'] = '';

        if ($status === 'list_lancar') {
    		$data['view'] = 'Lancar';
    	}

    	if ($status === 'list_kurang_lancar') {
    		$data['view'] = 'Kurang Lancar';
    	}

    	if ($status === 'list_diragukan') {
    		$data['view'] = 'Diragukan';
    	}

    	if ($status === 'list_macet') {
    		$data['view'] = 'Macet';
    	}

    	$q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->uri->segment(3));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . '.php/c_url/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'index.php/sale/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'index.php/sale/index/';
            $config['first_url'] = base_url() . 'index.php/sale/index/';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = FALSE;
        $config['total_rows'] = $this->Sale_model->total_rows_ka($q, $data['view']);
        $sale = $this->Sale_model->get_limit_data_ka($config['per_page'], $start, $q, $data['view']);
        $config['full_tag_open'] = '<ul class="pagination pagination-sm no-margin pull-right">';
        $config['full_tag_close'] = '</ul>';
        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'lists_data' => $sale,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'level_id' => $this->session->userdata('level_id'),
            'menu_accessed' => $this->uri->segment(1),
            'classnyak' => $this
        );

        $this->template->load('template','laporan/list_bb', $data);
    }

    function getDataSaldoAwalBB($status)
    {
        $data = $this->Laporan_model->getSaldoAwalBB($status);
        return $data;
    }

    function getDataAngsuranBB($status)
    {
        $data = $this->Laporan_model->getAngsuranlBB($status);
        return $data;
    }

    function getDataSaldoAkhirBB($status)
    {
        $data = $this->Laporan_model->getSaldoAkhirBB($status);
        return $data;
    }

    function getBrutoInvoiceterkini($inv)
    {
        $data = $this->Sale_detail_model->getBrutoTotalTerkini($inv)->harus_dibayar;
        return $data;
    }

    function getPokokInvoiceterkini($inv)
    {
        $data = $this->Sale_detail_model->getPokokTotalTerkini($inv)->pokok_cicilan;
        return $data;
    }


 //    public function read($id) 
 //    {
 //        is_allowed($this->uri->segment(1),'read');
 //        $row = $this->Jenis_item_model->get_by_id($id);
 //        if ($row) {
 //            $data = array(
	// 	'jenis_item_id' => $row->jenis_item_id,
	// 	'nama_jenis_item' => $row->nama_jenis_item,
	//     );
 //            $this->template->load('template','jenis_item/jenis_item_read', $data);
 //        } else {
 //            $this->session->set_flashdata('message', 'Record Not Found');
 //            redirect(site_url('jenis_item'));
 //        }
 //    }

 //    public function create() 
 //    {
 //        is_allowed($this->uri->segment(1),'create');
 //        $data = array(
 //            'button' => 'Create',
 //            'action' => site_url('jenis_item/create_action'),
	//     'jenis_item_id' => set_value('jenis_item_id'),
	//     'nama_jenis_item' => set_value('nama_jenis_item'),
	// );
 //        $this->template->load('template','jenis_item/jenis_item_form', $data);
 //    }

}

/* End of file Jenis_item.php */
/* Location: ./application/controllers/Jenis_item.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-01 08:38:23 */
/* http://harviacode.com */
