<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Approval_lists_model extends CI_Model
{

    public $table = 'approval_lists';
    public $id = 'approval_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('sale','sale.invoice = approval_lists.invoice_id');
        $this->db->where('unit_id', $this->session->userdata('unit_id'));
        return $this->db->get($this->table)->result();
    }

    // get data by id

    function get_by_invoice($id)
    {
        $this->db->where('invoice_id', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('approval_id', $q);
	$this->db->or_like('invoice_id', $q);
	$this->db->or_like('approve_by', $q);
    $this->db->or_like('jenis_tindakan', $q);
	$this->db->or_like('approval_status', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('komentar', $q);
	$this->db->from($this->table);
    $this->db->join('sale','sale.invoice = approval_lists.invoice_id');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('unit_id', $this->session->userdata('unit_id'));
        $this->db->group_start();
        $this->db->like('approval_id', $q);
    	$this->db->or_like('invoice_id', $q);
    	$this->db->or_like('approve_by', $q);
        $this->db->or_like('jenis_tindakan', $q);
    	$this->db->or_like('approval_status', $q);
        $this->db->group_end();
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where('invoice_id', $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Approval_lists_model.php */
/* Location: ./application/models/Approval_lists_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-14 14:49:50 */
/* http://harviacode.com */