<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Denda_model extends CI_Model
{

    public $table = 'denda';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where('sale_detail_id', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('grup_id', $q);
	$this->db->or_like('nama_grup', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('grup_id', $q);
	$this->db->or_like('nama_grup', $q);
    $this->db->or_like('kd_grup', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function update_by_sale_data_id($id, $data)
    {
        $this->db->where('sale_detail_id', $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function buat_kode(){
        $q = $this->db->query("SELECT MAX(RIGHT(kd_grup,3)) AS kd_max FROM grup");
        $kd = "";
        if($q->num_rows()>0){
            foreach($q->result() as $k){
                $tmp = ((int)$k->kd_max)+1;
                $kd = sprintf("%03s", $tmp);
            }
        }else{
            $kd = "001";
        }
        date_default_timezone_set('Asia/Jakarta');
        return $kd;
    }

    function getInfoDendaBerdasarkanInvoice($invoice)
    {
        $this->db->select('*')
            ->from($this->table)
            ->join('sale_detail','sale_detail.sale_detail_id = denda.sale_detail_id')
            ->where('sale_id',$invoice);
        return $this->db->get()->row();
    }

    function get_data_kwitansi($id)
    {
        $this->db->join('pelanggan','pelanggan.pelanggan_id = sale.pelanggan_id');
        $this->db->join('user','user.user_id = sale.user_id');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_invoice_profile($invoice)
    {
        $this->db->join('pelanggan','pelanggan.pelanggan_id = sale.pelanggan_id');
        $this->db->join('item','item.item_id = sale.item_id');
        $this->db->join('user','user.user_id = sale.user_id');
        $this->db->where('invoice', $invoice);
        return $this->db->get('sale')->row();
    }

}

/* End of file Grup_model.php */
/* Location: ./application/models/Grup_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-06 09:25:51 */
/* http://harviacode.com */