<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class History_pembayaran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where('pembayaran_detail_id', $id);
        return $this->db->get('history_pembayaran')->row();
    }

    function getDataHistoryPembayaran($invoice, $jenispembayaraan, $filter = NULL)
    {
        $where = array(
            'id' => $invoice,
            'jenis_pembayaran' => $jenispembayaraan,
            'deskripsi' => $filter
        );
        $this->db->select('*');
        $this->db->where($where);
        $this->db->order_by('tanggal_bayar','ASC');
        return $this->db->get('history_pembayaran')->result();
    }

    function getSingleDataHistoryPembayaran($invoice, $jenispembayaraan)
    {
        $where = array(
            'id' => $invoice,
            'jenis_pembayaran' => $jenispembayaraan
        );
        $this->db->select('*');
        $this->db->where($where);
        return $this->db->get('history_pembayaran')->row();
    }

}

/* End of file History_login_model.php */
/* Location: ./application/models/History_login_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-06 09:36:35 */
/* http://harviacode.com */