<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kendaraan_model extends CI_Model
{

    public $table = 'kendaraan';
    public $id = 'kendaraan_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kendaraan_id', $q);
	$this->db->or_like('kd_motor', $q);
	$this->db->or_like('nama_kendaraan', $q);
	$this->db->or_like('jenis_kendaraan_id', $q);
	$this->db->or_like('merek_id', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('stok', $q);
	$this->db->or_like('photo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('jenis_kendaraan', 'jenis_kendaraan.jenis_kendaraan_id = kendaraan.jenis_kendaraan_id', 'left');
        $this->db->join('merek', 'merek.merek_id = kendaraan.merek_id', 'left');
        $this->db->order_by($this->id, $this->order);
        $this->db->group_start();
        $this->db->like('kendaraan_id', $q);
	$this->db->or_like('kd_motor', $q);
	$this->db->or_like('nama_kendaraan', $q);
	$this->db->or_like('jenis_kendaraan.nama_jenis_kendaraan', $q);
	$this->db->or_like('merek.nama_merek', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('stok', $q);
    $this->db->group_end();
	$this->db->or_like('photo', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kendaraan_model.php */
/* Location: ./application/models/Kendaraan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-01 08:37:31 */
/* http://harviacode.com */