<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Laporan_model extends CI_Model
{

    function __construct()
    {
        parent::__construct();
    }

    function getSaldoAwalBB($keadaancicilan)
    {
        $query = "
            SELECT SUM(sale_detail.pokok_cicilan) as 'Pokok',(SUM(sale_detail.harus_dibayar) - SUM(sale_detail.pokok_cicilan)) as 'Bunga'
            FROM sale_detail
            JOIN sale ON sale.invoice = sale_detail.sale_id
            LEFT JOIN item ON item.item_id = sale.item_id
            WHERE sale_detail.sale_id = sale.invoice AND item.unit_id = ".$this->session->userdata('unit_id')." AND sale.keadaan_cicilan = '".$keadaancicilan."';
        ";
        return $this->db->query($query)->row();
    }

    function getAngsuranlBB($keadaancicilan)
    {
        $query = "
            SELECT SUM(sale_detail.pokok_cicilan) as 'Pokok',(SUM(sale_detail.harus_dibayar) - SUM(sale_detail.pokok_cicilan)) as 'Bunga'
            FROM sale_detail
            JOIN sale ON sale.invoice = sale_detail.sale_id
            LEFT JOIN item ON item.item_id = sale.item_id
            WHERE sale_detail.sale_id = sale.invoice AND item.unit_id = ".$this->session->userdata('unit_id')." AND sale_detail.status = 'dibayar' AND sale.keadaan_cicilan = '".$keadaancicilan."';
        ";
        return $this->db->query($query)->row();
    }

    function getSaldoAkhirBB($keadaancicilan)
    {
        $query = "
            SELECT SUM(sale_detail.pokok_cicilan) as 'Pokok',(SUM(sale_detail.harus_dibayar) - SUM(sale_detail.pokok_cicilan)) as 'Bunga'
            FROM sale_detail
            JOIN sale ON sale.invoice = sale_detail.sale_id
            LEFT JOIN item ON item.item_id = sale.item_id
            WHERE sale_detail.sale_id = sale.invoice AND item.unit_id = ".$this->session->userdata('unit_id')." AND (sale_detail.status = 'siap dibayar' OR sale_detail.status = 'belum siap dibayar') AND sale.keadaan_cicilan = '".$keadaancicilan."';
        ";
        return $this->db->query($query)->row();
    }

 //    // get all
 //    function get_all()
 //    {
 //        $this->db->order_by($this->id, $this->order);
 //        return $this->db->get($this->table)->result();
 //    }

 //    // get data by id
 //    function get_by_id($id)
 //    {
 //        $this->db->where($this->id, $id);
 //        return $this->db->get($this->table)->row();
 //    }
    
 //    // get total rows
 //    function total_rows($q = NULL) {
 //        $this->db->like('kategori_id', $q);
	// $this->db->or_like('nama_kategori', $q);
	// $this->db->from($this->table);
 //        return $this->db->count_all_results();
 //    }

 //    // get data with limit and search
 //    function get_limit_data($limit, $start = 0, $q = NULL) {
 //        $this->db->order_by($this->id, $this->order);
 //        $this->db->like('kategori_id', $q);
	// $this->db->or_like('nama_kategori', $q);
	// $this->db->limit($limit, $start);
 //        return $this->db->get($this->table)->result();
 //    }

 //    // insert data
 //    function insert($data)
 //    {
 //        $this->db->insert($this->table, $data);
 //    }

 //    // update data
 //    function update($id, $data)
 //    {
 //        $this->db->where($this->id, $id);
 //        $this->db->update($this->table, $data);
 //    }

 //    // delete data
 //    function delete($id)
 //    {
 //        $this->db->where($this->id, $id);
 //        $this->db->delete($this->table);
 //    }

}

/* End of file Kategori_model.php */
/* Location: ./application/models/Kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-04 20:20:13 */
/* http://harviacode.com */