<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Menu_model extends CI_Model
{

    public $table = 'menu';
    public $id = 'menu_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    public function get($menu_id = null)
    {
        $this->db->from('menu');
        if ($menu_id !=null){
            $this->db->where('menu_id', $menu_id);
        }
        $this->db->order_by("urutan","asc");
        $query = $this->db->get();
        return $query;
    }

    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getDynamicMnu($an)
    {
        /*SELECT `user_access_menu`.`user_access_menu_id`,`level_id`,`menu`.`menu`,`menu`.`icon`,`menu`.`menu_id` as menu_id
            FROM `user_access_menu` JOIN `sub_menu` 
              ON `user_access_menu`.`sub_menu_id` = `sub_menu`.`sub_menu_id`
              JOIN `menu` 
              ON `menu`.`menu_id` = `sub_menu`.`menu_id`
           WHERE `user_access_menu`.`level_id` = $session_level_id
           GROUP BY `menu`.`menu_id`
              ORDER BY `menu`.`urutan` ASC
           ";*/

        $this->db->select('user_access_menu.user_access_menu_id,level_id,menu.menu,menu.icon,menu.menu_id as menu_id')
            ->from('user_access_menu')
            ->join('sub_menu','sub_menu.sub_menu_id = user_access_menu.sub_menu_id')
    }

}

/* End of file menu_model.php */
/* Location: ./application/models/menu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-28 13:00:38 */
/* http://harviacode.com */
