<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sale_model extends CI_Model
{

    public $table = 'sale';
    public $id = 'sale_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('user', 'user.user_id = sale.user_id');
        $this->db->join('pelanggan', 'pelanggan.pelanggan_id = sale.pelanggan_id');
        $this->db->join('item', 'item.item_id = sale.item_id','left');
        $this->db->join('merek', 'merek.merek_id = item.merek_id','left');
        $this->db->join('type', 'type.type_id = item.type_id','left');
        
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('pelanggan','pelanggan.pelanggan_id = sale.pelanggan_id');
        $this->db->join('item','item.item_id = sale.item_id');
        $this->db->join('user','user.user_id = sale.user_id');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('sale_id', $q);
    	$this->db->or_like('invoice', $q);
    	$this->db->or_like('pelanggan_id', $q);
    	$this->db->or_like('item_id', $q);
    	$this->db->or_like('total_price_sale', $q);
    	$this->db->or_like('type_sale', $q);
    	$this->db->or_like('tanggal_sale', $q);
    	$this->db->or_like('user_id', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('user', 'user.user_id = sale.user_id', 'left');
        $this->db->join('pelanggan', 'pelanggan.pelanggan_id = sale.pelanggan_id', 'left');
        $this->db->join('item', 'item.item_id = sale.item_id', 'left');
        $this->db->order_by($this->id, $this->order);
        $this->db->group_start();
        $this->db->like('sale_id', $q);
    	$this->db->or_like('invoice', $q);
    	$this->db->or_like('pelanggan.nama_pelanggan', $q);
    	$this->db->or_like('item.nama_item', $q);
    	$this->db->or_like('total_price_sale', $q);
    	$this->db->or_like('type_sale', $q);
    	$this->db->or_like('tanggal_sale', $q);
    	$this->db->or_like('user.nama_user', $q);
        $this->db->group_end();
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($tipesale, $data, $datacicilan = NULL)
    {
        if ($tipesale == 'Kredit') {
            $this->db->insert($this->table, $data);
            foreach($datacicilan as $k) {
                $this->db->insert('sale_detail', $k);
            }
            return;
        }

        $this->db->insert($this->table, $data);
        return;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    
    function buat_kode(){
        $q = $this->db->query("SELECT MAX(RIGHT(invoice,4)) AS kd_max FROM sale WHERE DATE(tanggal_sale)=CURDATE()");
        $kd = "";
        if($q->num_rows()>0){
            foreach($q->result() as $k){
                $tmp = ((int)$k->kd_max)+1;
                $kd = sprintf("%04s", $tmp);
            }
        }else{
            $kd = "0001";
        }
        date_default_timezone_set('Asia/Jakarta');
        return 'S'.date('dmy').$kd;
    }}

/* End of file Sale_model.php */
/* Location: ./application/models/Sale_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-03 11:10:29 */
/* http://harviacode.com */
