<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sub_unit_model extends CI_Model
{

    public $table = 'sub_unit';
    public $id = 'sub_unit_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('sub_unit_id', $q);
	$this->db->or_like('unit_id', $q);
	$this->db->or_like('nama_sub_unit', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('unit', 'unit.unit_id = sub_unit.unit_id', 'left');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('sub_unit_id', $q);
	$this->db->or_like('unit.nama_unit', $q);
	$this->db->or_like('nama_sub_unit', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function buat_kode(){
        $q = $this->db->query("SELECT MAX(RIGHT(kd_sub_unit,3)) AS kd_max FROM sub_unit");
        $kd = "";
        if($q->num_rows()>0){
            foreach($q->result() as $k){
                $tmp = ((int)$k->kd_max)+1;
                $kd = sprintf("%03s", $tmp);
            }
        }else{
            $kd = "001";
        }
        date_default_timezone_set('Asia/Jakarta');
        return $kd;
    }

}

/* End of file Sub_unit_model.php */
/* Location: ./application/models/Sub_unit_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-06 10:11:15 */
/* http://harviacode.com */