

    <?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sub_menu_model extends CI_Model
{

    public $table = 'sub_menu';
    public $id = 'sub_menu_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

     public function get($id = null)
    {
        $this->db->select('sub_menu.*,menu.menu');
        $this->db->from('sub_menu');
        $this->db->join('menu', 'menu.menu_id = sub_menu.menu_id');
        if ($id !=null){
            $this->db->where('sub_menu.menu_id', $id);
        }
        $query = $this->db->get();
        return $query;
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file sub_menu_model.php */
/* Location: ./application/models/sub_menu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-28 13:00:38 */
/* http://harviacode.com */