<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Unit_model extends CI_Model
{

    public $table = 'unit';
    public $id = 'unit_id';
    public $table2 = 'user_access_unit';
    public $id2 = 'user_access_unit_id';

    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_access()
    {
        $user_id = $this->fungsi->user_login()->user_id;
        $this->db->join('unit', 'unit.unit_id = user_access_unit.unit_id', 'left');
        $this->db->join('grup', 'grup.grup_id = unit.grup_id', 'left');
        $this->db->order_by('kd_unit', 'ASC');
        $this->db->where('user_id',$user_id);
        return $this->db->get($this->table2)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('unit_id', $q);
	$this->db->or_like('grup_id', $q);
	$this->db->or_like('nama_unit', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('grup', 'grup.grup_id = unit.grup_id', 'left');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('unit_id', $q);
	$this->db->or_like('grup.nama_grup', $q);
	$this->db->or_like('nama_unit', $q);
    $this->db->or_like('kd_unit', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

     function buat_kode(){
        $q = $this->db->query("SELECT MAX(RIGHT(kd_unit,3)) AS kd_max FROM unit");
        $kd = "";
        if($q->num_rows()>0){
            foreach($q->result() as $k){
                $tmp = ((int)$k->kd_max)+1;
                $kd = sprintf("%03s", $tmp);
            }
        }else{
            $kd = "001";
        }
        date_default_timezone_set('Asia/Jakarta');
        return $kd;
    }

}

/* End of file Unit_model.php */
/* Location: ./application/models/Unit_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-06 10:09:22 */
/* http://harviacode.com */